version: "3.4"

services:

    webserver_numerico:
        build: ./build/webserver
        container_name: numerico_webserver
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - certs:/etc/letsencrypt
            - ./volumes/calculonumerico_webfiles:/var/www/html
        depends_on:
            - letsencrypt_numerico
        networks:
            - webserver
            - letsencrypt
            - php
        environment:
            - APPS_NUMBER=${APPS_NUMBER}
            - APPNAME1=${APPNAME1}
            - DOMAIN1=${DOMAIN1}
            - FQDN=${FQDN}
            - DOMAIN=${DOMAIN}
        command: /bin/bash -c "genAppNginx -n ${APPS_NUMBER} -o /etc/nginx/conf.d/ && nginx -g 'daemon off;'"

    letsencrypt_numerico:
        build: ./build/letsencrypt
        container_name: numerico_letsencrypt
        restart: always
        volumes:
            - certs:/etc/letsencrypt
        depends_on:
            - php_numerico
        networks:
            - letsencrypt
        environment:
            - FQDN=${FQDN}
            - DOMAIN=${DOMAIN}
            - EMAIL_LETS=${EMAIL_LETS}

    php_numerico:
        build: ./build/php
        container_name: numerico_php
        restart: always
        volumes:
            - ./volumes/calculonumerico_webfiles:/var/www/html
        networks:
             - php
        environment:
            - TOKEN=${TOKEN}
            - REPOSITORIO=${REPOSITORIO}
            - RAMO=${RAMO}
            - DIRETORIO=${DIRETORIO}
        command: /bin/bash -c "envsubst '$${TOKEN} $${REPOSITORIO} $${RAMO} $${DIRETORIO}' < hooks/deploy-config-example.php > hooks/deploy-config.php && php-fpm"

volumes:
    certs:

networks:
    webserver:
    letsencrypt:
    php:
